// <auto-generated/>
using Microsoft.OpenApi.Models;
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddControllers();
builder.Services.AddCors(o => o.AddPolicy("Client", p =>
    p.WithOrigins("http://localhost:5173", "http://localhost:8081").AllowAnyHeader().AllowAnyMethod()
));
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c => c.SwaggerDoc("v1", new OpenApiInfo { Title = "server", Version = "v1" }));
var app = builder.Build();
app.UseCors("Client");
bool enableSwagger = app.Environment.IsDevelopment() ||
    string.Equals(Environment.GetEnvironmentVariable("ENABLE_SWAGGER"), "true", StringComparison.OrdinalIgnoreCase);
if (enableSwagger) {
    app.UseSwagger();
    app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "server v1"));
    if (app.Environment.IsDevelopment())
        app.MapGet("/", ctx => { ctx.Response.Redirect("/swagger"); return Task.CompletedTask; });
}
app.MapControllers();
app.Run();
